# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'annotationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from annotationSet import annotationSet


class Ui_annotationDialog(object):
    def setupUi(self, annotationDialog):
        annotationDialog.setObjectName("annotationDialog")
        annotationDialog.resize(371, 234)
        self.annotationset = annotationSet()
        self.position = 0
        self.gridLayout = QtWidgets.QGridLayout(annotationDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.typelabel = QtWidgets.QLabel(annotationDialog)
        self.typelabel.setObjectName("typelabel")
        self.gridLayout.addWidget(self.typelabel, 0, 0, 1, 1)
        self.typeEdit = QtWidgets.QLineEdit(annotationDialog)
        self.typeEdit.setObjectName("typeEdit")
        self.gridLayout.addWidget(self.typeEdit, 0, 1, 1, 2)
        self.commentLabel = QtWidgets.QLabel(annotationDialog)
        self.commentLabel.setObjectName("commentLabel")
        self.gridLayout.addWidget(self.commentLabel, 1, 0, 1, 1)
        self.commentEdit = QtWidgets.QLineEdit(annotationDialog)
        self.commentEdit.setObjectName("commentEdit")
        self.gridLayout.addWidget(self.commentEdit, 1, 1, 1, 2)
        self.saveButton = QtWidgets.QPushButton(annotationDialog)
        self.saveButton.setObjectName("saveButton")
        self.saveButton.clicked.connect(self.saveButton)
        self.gridLayout.addWidget(self.saveButton, 2, 1, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(annotationDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 2, 2, 1, 1)

        self.retranslateUi(annotationDialog)
        QtCore.QMetaObject.connectSlotsByName(annotationDialog)

    def retranslateUi(self, annotationDialog):
        _translate = QtCore.QCoreApplication.translate
        annotationDialog.setWindowTitle(_translate("annotationDialog", "Dialog"))
        self.typelabel.setText(_translate("annotationDialog", "Type"))
        self.commentLabel.setText(_translate("annotationDialog", "Comment"))
        self.saveButton.setText(_translate("annotationDialog", "Save"))
        self.cancelButton.setText(_translate("annotationDialog", "Cancel"))

    def saveButton(self):
        self.annotationset.annotate(self.position, self.typeEdit.text(), self.commentEdit.text())

    def setPosition(self, position):
        self.position = position


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    annotationDialog = QtWidgets.QDialog()
    ui = Ui_annotationDialog()
    ui.setupUi(annotationDialog)
    annotationDialog.show()
    sys.exit(app.exec_())
