# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1205, 916)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 701, 841))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        
        self.FaceCamera = QVideoWidget(self.frame)
        self.FaceCamera.setGeometry(QtCore.QRect(20, 370, 661, 351))
        self.FaceCamera.setObjectName("FaceCamera")
        
        self.horizontalSlider = QtWidgets.QSlider(self.frame)
        self.horizontalSlider.setGeometry(QtCore.QRect(70, 730, 541, 31))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        
        self.CameraFeed = QVideoWidget(self.frame)
        self.CameraFeed.setGeometry(QtCore.QRect(20, 10, 661, 351))
        self.CameraFeed.setAcceptDrops(False)
        self.CameraFeed.setObjectName("CameraFeed")
        
        self.pushButton_5 = QtWidgets.QPushButton(self.CameraFeed)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 140, 131, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 730, 31, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        
        self.Sync = QtWidgets.QPushButton(self.frame)
        self.Sync.setGeometry(QtCore.QRect(520, 800, 171, 31))
        self.Sync.setObjectName("Sync")
        
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 800, 171, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        
        self.labelET = QtWidgets.QLabel(self.frame)
        self.labelET.setGeometry(QtCore.QRect(30, 770, 141, 20))
        self.labelET.setObjectName("labelET")
        
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(520, 780, 171, 16))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        
        self.label_2speed = QtWidgets.QLabel(self.frame)
        self.label_2speed.setGeometry(QtCore.QRect(30, 790, 141, 20))
        self.label_2speed.setObjectName("label_2speed")
        
        self.label_3error = QtWidgets.QLabel(self.frame)
        self.label_3error.setGeometry(QtCore.QRect(620, 730, 61, 31))
        self.label_3error.setObjectName("label_3error")
        
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(730, 10, 461, 461))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 20, 161, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 20, 181, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        
        self.toolButton = QtWidgets.QToolButton(self.frame_2)
        self.toolButton.setGeometry(QtCore.QRect(400, 410, 31, 31))
        self.toolButton.setObjectName("toolButton")
        
        self.toolButton_2 = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_2.setGeometry(QtCore.QRect(30, 410, 31, 31))
        self.toolButton_2.setObjectName("toolButton_2")
        
        self.tableView = QtWidgets.QTableView(self.frame_2)
        self.tableView.setGeometry(QtCore.QRect(30, 60, 401, 331))
        self.tableView.setObjectName("tableView")
        
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(729, 489, 461, 361))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(260, 140, 161, 31))
        self.pushButton.setObjectName("pushButton")
        
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        self.comboBox.setGeometry(QtCore.QRect(30, 140, 211, 31))
        self.comboBox.setObjectName("comboBox")
        
        MainWindow.setCentralWidget(self.centralwidget)

        #Menu
        
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1205, 26))
        self.menubar.setObjectName("menubar")
        
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.actionAdd_Video = QtWidgets.QAction(MainWindow)
        self.actionAdd_Video.setObjectName("actionAdd_Video")
        self.actionAdd_CSV_File = QtWidgets.QAction(MainWindow)
        self.actionAdd_CSV_File.setObjectName("actionAdd_CSV_File")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        
        self.menuFile.addAction(self.actionAdd_Video)
        self.menuFile.addAction(self.actionAdd_CSV_File)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_5.setText(_translate("MainWindow", "Add Camera Feed"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton"))
        self.Sync.setText(_translate("MainWindow", "Sync Video"))
        self.pushButton_2.setText(_translate("MainWindow", "Add Audio Snippet"))
        self.labelET.setText(_translate("MainWindow", "ElapsedTime"))
        self.label_2speed.setText(_translate("MainWindow", "Speed"))
        self.label_3error.setText(_translate("MainWindow", "Speed"))
        self.pushButton_3.setText(_translate("MainWindow", "Add Objects"))
        self.pushButton_4.setText(_translate("MainWindow", "Delete objects"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.pushButton.setText(_translate("MainWindow", "Visualize Data"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAdd_Video.setText(_translate("MainWindow", "Add Video"))
        self.actionAdd_CSV_File.setText(_translate("MainWindow", "Add CSV File"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as.."))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
from PyQt5.QtMultimediaWidgets import QVideoWidget

if __name__ == '__main__':
    import sys
    app = QApplication(sys.argv)
    mainW = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainW)
    # player.resize(640, 480)
    mainW.show()
    sys.exit(app.exec_())

